# -*- coding: utf-8 -*-
"""Collect_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19stkw6lj4akgaPcxiWM7LVpcyPp3w07k
"""

import requests
import csv

API_KEY = "54afb5199a1902651e15221e0dd280d7"
CITY = "Lahore"  # or your desired city
URL = f"http://api.openweathermap.org/data/2.5/forecast?q={CITY}&appid={API_KEY}&units=metric"

def collect_data(source_file='raw_data.csv', target_file='collected_data.csv'):
    response = requests.get(URL)
    data = response.json()

    if data.get("cod") != "200":
        print(f"Error: {data.get('message', 'Unknown error')}")
        return

    with open(target_file, mode="w", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(["Date and Time", "Temperature (°C)", "Humidity (%)", "Wind Speed (m/s)", "Weather Condition"])

        for entry in data["list"]:
            dt_txt = entry["dt_txt"]
            temp = entry["main"]["temp"]
            humidity = entry["main"]["humidity"]
            wind_speed = entry["wind"]["speed"]
            condition = entry["weather"][0]["description"]

            writer.writerow([dt_txt, temp, humidity, wind_speed, condition])

    print(f"✅ Weather data saved to {target_file}")